services:
  db:
    image: postgres:15
    container_name: odoo19-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:19
    container_name: odoo19-app
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./custom_addons:/mnt/extra-addons
      - odoo-web-data:/var/lib/odoo
    restart: unless-stopped

volumes:
  odoo-db-data:
  odoo-web-data:
